version: '2'
services:
   db15:
        image: postgres:13
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=odoo
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
                - db15-data=/var/lib/postgresql/data/pgdata
        networks:
                - network-15
   odoo15:
        image: odoo:15.0
        command: --dev=all
        ports:
                - 8015:8069
        links:
                - db15:db
        volumes:
                - ./config:/etc/odoo
                - .:/mnt/extra-addons
                - /home/b14/odoo-dev/odoo_enterprise/odoo/addons:/mnt/enterprise
                - odoo15-data:/var/lib/odoo
        networks:
                - network-15
volumes:
        odoo15-data:
        db15-data:
networks:
        network-15:
