version: '2'
services:
   db:
        image: postgres:<version>
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=odoo
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql14/data/pgdata
        volumes:
                - db<version>-data=/var/lib/postgresql14/data/pgdata
   odoo14:
        image: odoo:<version>
        command: --dev=all
        ports:
                - <port>:8069
        links:
                - db:db
        volumes:
                - ./config:/etc/odoo
                - .:/mnt/extra-addons
                - odoo<version>-data:/var/lib/odoo
volumes:
        odoo<version>-data:
        db<version>-data:
