version: '2'
services:
   db:
        image: postgres:13
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=odoo
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
                - db-data=/var/lib/postgresql/data/pgdata
   odoo1:
        image: odoo:14
        ports:
                - 8069:8069
        links:
                - db:db
        volumes:
                - ./config:/etc/odoo
                - .:/mnt/extra-addons  
                - odoo1-data:/var/lib/odoo
   odoo2:
        image: odoo:14
        ports:
                - 8014:8069
        links:
                - db:db
        volumes:
                - ./config:/etc/odoo
                - .:/mnt/extra-addons              
                - odoo2-data:/var/lib/odoo

volumes:
        odoo1-data:
        odoo2-data:
        db-data:
