version: '2'
services:
   db:
        image: postgres:12
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=odoo
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql14/data/pgdata
        volumes:
                - db13-data=/var/lib/postgresql14/data/pgdata
   odoo:
        image: odoo:13.0
        command: --dev=all
        ports:
                - 8013:8069
        links:
                - db:db
        volumes:
                - ./config:/etc/odoo
                - .:/mnt/extra-addons
                - /home/b14/odoo-dev/custom-addons13/enterprise:/mnt/enterprise
                - odoo13-data:/var/lib/odoo
volumes:
        odoo13-data:
        db13-data:
